### PR TITLE
Checkbox displays task priorities

### PR DESCRIPTION
**Pull request by ChausseBenjamin**
With this patch, the checkbox should use the priority colors that Todoist
normally uses.

- Priority 1: #D1453B
- Priority 2: #EB8909
- Priority 3: #246FE0
- Priority 4: Regular text color ('todoistCheckbox')

The only problem with my pr is that you used the checkbox `hl` to show
errors(i.e. `const hl = i.error ? 'todoistError' : 'todoistCheckbox'`).  I
suggest you find an other implementation to signal errors to the user...

### CODE REVIEW

**Comment by ChausseBenjamin** [comment]
@romgrk Do you know of a way I can test the error function? I'd love to test an alternative implementation since my patch for priority colours removes it. I just need a way for it to be triggered manually and reliably. ;)

**Comment by romgrk** [comment]
Maybe try switching your internet off, then try to update the item?

**Comment by ChausseBenjamin** [comment]
PR should be ok to merge now.

**Comment by romgrk** [comment]
Sorry about the delay, thanks.

**Pull request merged**
